apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: web
spec:
  rules:
    - host: guidebook.demo.com
      http:
        paths:
          - backend:
              serviceName: guestbook-ui
              servicePort: 80